"""ai moderation fields

Revision ID: 30f1da2e5e97
Revises: 693ba770d425
Create Date: 2026-10-06 10:49:49.088063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f1da2e5e97'
down_revision: Union[str, Sequence[str], None] = '693ba770d425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_verdict', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_risk', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ai_reasons', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('ai_checked_at')
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('ai_reasons')
        batch_op.drop_column('ai_risk')
        batch_op.drop_column('ai_verdict')

    # ### end Alembic commands ###
