"""fraud hold

Revision ID: 44dc51ce61f5
Revises: 5281c685c3d0
Create Date: 2026-10-07 18:22:47.694574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44dc51ce61f5'
down_revision: Union[str, Sequence[str], None] = '5281c685c3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index('ix_clicks_ip_hash_time_window', ['ip_hash', 'time_window'], unique=False)

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fraud_hold', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('fraud_reviewed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('fraud_reviewed_at')
        batch_op.drop_column('fraud_hold')

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index('ix_clicks_ip_hash_time_window')

    # ### end Alembic commands ###
