"""site auto check

Revision ID: 4a71abc75661
Revises: 59e27c5d53d5
Create Date: 2026-10-07 16:34:57.143495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a71abc75661'
down_revision: Union[str, Sequence[str], None] = '59e27c5d53d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_verdict', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('check_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('check_reasons', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('checked_at')
        batch_op.drop_column('check_reasons')
        batch_op.drop_column('check_summary')
        batch_op.drop_column('check_verdict')

    # ### end Alembic commands ###
