"""auction and placement stats

Revision ID: 4ac66e1c75e6
Revises: f699f89dbf7e
Create Date: 2026-10-07 14:57:34.326917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac66e1c75e6'
down_revision: Union[str, Sequence[str], None] = 'f699f89dbf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_daily_stats',
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('placement_id', 'day')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpc_bid', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.alter_column('placement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_check_constraint('ck_campaigns_cpc_bid_positive', 'cpc_bid IS NULL OR cpc_bid > 0')

    # ### end Alembic commands ###
    # Статистика площадок за прошлые дни — из статистики кампаний: до этой версии у каждой кампании
    # была своя площадка, поэтому отчёт «по площадкам» после обновления показывает те же цифры
    op.execute(
        "INSERT INTO placement_daily_stats (placement_id, day, impressions, clicks, spend) "
        "SELECT c.placement_id, d.day, SUM(d.impressions), SUM(d.clicks), SUM(d.spend) "
        "FROM campaign_daily_stats d JOIN campaigns c ON c.id = d.campaign_id "
        "GROUP BY c.placement_id, d.day"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Кампании на всю сеть (без площадки) в старой схеме не выразить — откат только без них
    count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM campaigns WHERE placement_id IS NULL")).scalar()
    if count:
        raise RuntimeError(f"Откат невозможен: {count} кампаний на всю сеть (placement_id IS NULL). "
                           "Назначьте им площадку или удалите их")
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('ck_campaigns_cpc_bid_positive', type_='check')
        batch_op.alter_column('placement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cpc_bid')

    op.drop_table('placement_daily_stats')
    # ### end Alembic commands ###
