"""notifications

Revision ID: 5281c685c3d0
Revises: 4a71abc75661
Create Date: 2026-10-07 16:45:20.119850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5281c685c3d0'
down_revision: Union[str, Sequence[str], None] = '4a71abc75661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), server_default='en', nullable=False))
        batch_op.add_column(sa.Column('low_balance_notified', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('low_balance_notified')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
