"""auth attempts and token version

Revision ID: 5ef8aa5160ad
Revises: e0f9b5b3ec0e
Create Date: 2026-10-05 19:51:29.562488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef8aa5160ad'
down_revision: Union[str, Sequence[str], None] = 'e0f9b5b3ec0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_auth_attempts_kind_key_ts', ['kind', 'key', 'ts'], unique=False)
        batch_op.create_index('ix_auth_attempts_ts', ['ts'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    with op.batch_alter_table('auth_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_attempts_ts')
        batch_op.drop_index('ix_auth_attempts_kind_key_ts')

    op.drop_table('auth_attempts')
    # ### end Alembic commands ###
