"""transactions counter

Revision ID: 693ba770d425
Revises: 5ef8aa5160ad
Create Date: 2026-10-05 20:14:38.312680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693ba770d425'
down_revision: Union[str, Sequence[str], None] = '5ef8aa5160ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactions_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Счётчик для уже существующих записей журнала (иначе total истории был бы 0)
    op.execute(
        "UPDATE users SET transactions_count = "
        "(SELECT COUNT(*) FROM transactions WHERE transactions.user_id = users.id)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('transactions_count')

    # ### end Alembic commands ###
