"""site verification

Revision ID: 82fee3db70e2
Revises: 44dc51ce61f5
Create Date: 2026-10-07 18:30:19.289994

"""
from typing import Sequence, Union

import secrets
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fee3db70e2'
down_revision: Union[str, Sequence[str], None] = '44dc51ce61f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###
    # Уже добавленным сайтам — свой код подтверждения; одобренные администратором раньше (до появления
    # подтверждения) считаются подтверждёнными: работающие партнёры после обновления ничего не теряют
    bind = op.get_bind()
    sites = sa.table("sites", sa.column("id", sa.Integer), sa.column("status", sa.String),
                     sa.column("verify_token", sa.String), sa.column("verified_at", sa.DateTime(timezone=True)))
    now = datetime.now(timezone.utc)
    for site_id, status in bind.execute(sa.select(sites.c.id, sites.c.status)).all():
        bind.execute(sites.update().where(sites.c.id == site_id).values(
            verify_token=secrets.token_hex(16),
            verified_at=now if status in ("approved", "blocked") else None))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verify_token')

    # ### end Alembic commands ###
