"""optimize indexes

Revision ID: be4c321c0dbf
Revises: 6ab9a954cadd
Create Date: 2026-10-05 17:48:07.252486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4c321c0dbf'
down_revision: Union[str, Sequence[str], None] = '6ab9a954cadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_placement_id'))
        batch_op.create_index('ix_campaigns_placement_status', ['placement_id', 'status'], unique=False)

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clicks_campaign_id'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.create_index('ix_transactions_user_id_id', ['user_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_id_id')
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clicks_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_placement_status')
        batch_op.create_index(batch_op.f('ix_campaigns_placement_id'), ['placement_id'], unique=False)

    # ### end Alembic commands ###
