"""fraud controls

Revision ID: d351e51761fe
Revises: dbce14449452
Create Date: 2026-10-07 15:55:40.331459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd351e51761fe'
down_revision: Union[str, Sequence[str], None] = 'dbce14449452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_clicks_placement_id_time_window', ['placement_id', 'time_window'], unique=False)
        batch_op.create_foreign_key('fk_clicks_placement_id', 'placements', ['placement_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('partner_earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forfeited', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_earnings', schema=None) as batch_op:
        batch_op.drop_column('forfeited')

    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clicks_placement_id', type_='foreignkey')
        batch_op.drop_index('ix_clicks_placement_id_time_window')
        batch_op.drop_column('placement_id')

    # ### end Alembic commands ###
