"""referrals

Revision ID: dbce14449452
Revises: 4ac66e1c75e6
Create Date: 2026-10-07 15:08:03.952968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbce14449452'
down_revision: Union[str, Sequence[str], None] = '4ac66e1c75e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_referred_by_id'), ['referred_by_id'], unique=False)
        batch_op.create_unique_constraint('uq_users_referral_code', ['referral_code'])
        batch_op.create_foreign_key('fk_users_referred_by_id', 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_referred_by_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_referral_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_referred_by_id'))
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
