"""ai tasks query indexes

Revision ID: df517bab5067
Revises: 614e38c3a62e
Create Date: 2026-10-06 15:19:33.447748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df517bab5067'
down_revision: Union[str, Sequence[str], None] = '614e38c3a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_ai_tasks_status_updated_at', ['status', 'updated_at'], unique=False)
        batch_op.create_index('ix_ai_tasks_user_id_status_created_at', ['user_id', 'status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_tasks_user_id_status_created_at')
        batch_op.drop_index('ix_ai_tasks_status_updated_at')

    # ### end Alembic commands ###
