"""partner program

Revision ID: f699f89dbf7e
Revises: 656edb043e3e
Create Date: 2026-10-07 14:47:57.819686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f699f89dbf7e'
down_revision: Union[str, Sequence[str], None] = '656edb043e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_earnings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('site', 'referral', name='earning_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('matured', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'day', 'source')
    )
    with op.batch_alter_table('partner_earnings', schema=None) as batch_op:
        batch_op.create_index('ix_partner_earnings_matured_day', ['matured', 'day'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'rejected', name='payout_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_payouts_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index('ix_payouts_status_id', ['status', 'id'], unique=False)
        batch_op.create_index('ix_payouts_user_id_id', ['user_id', 'id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'blocked', name='site_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('revenue_share', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revenue_share IS NULL OR (revenue_share >= 0 AND revenue_share <= 1)', name='ck_sites_revenue_share'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_status'), ['status'], unique=False)
        batch_op.create_index('ix_sites_user_id_id', ['user_id', 'id'], unique=False)

    op.create_table('partner_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.Enum('earning', 'payout', 'payout_return', 'to_balance', name='partner_tx_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_partner_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_partner_transactions_user_id_id', ['user_id', 'id'], unique=False)

    op.create_table('site_daily_stats',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('earnings', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('site_id', 'day')
    )
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_placements_site_id'), ['site_id'], unique=False)
        batch_op.create_foreign_key('fk_placements_site_id', 'sites', ['site_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earnings_balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
        batch_op.create_check_constraint('ck_users_earnings_balance_nonneg', 'earnings_balance >= 0')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_earnings_balance_nonneg', type_='check')
        batch_op.drop_column('earnings_balance')

    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_placements_site_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_placements_site_id'))
        batch_op.drop_column('site_id')

    op.drop_table('site_daily_stats')
    with op.batch_alter_table('partner_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_transactions_user_id_id')

    op.drop_table('partner_transactions')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index('ix_sites_user_id_id')
        batch_op.drop_index(batch_op.f('ix_sites_status'))

    op.drop_table('sites')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_payouts_user_id_id')
        batch_op.drop_index('ix_payouts_status_id')

    op.drop_table('payouts')
    with op.batch_alter_table('partner_earnings', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_earnings_matured_day')

    op.drop_table('partner_earnings')
    # ### end Alembic commands ###
